# Generated by `nimbus-release render-formula` for the 0.1.0 release.
# Do not edit by hand: the next release overwrites it.
class Nimbus < Formula
  desc "Deploy and manage apps on Nimbus Land"
  homepage "https://get.nimbusland.ca"
  version "0.1.0"
  license :cannot_represent

  # Stable versions only: pre-release links ("v0.6.0-rc.1/") don't match.
  # (A JSON livecheck on /cli/latest.json would be nicer, but Homebrew's
  # LivecheckUrlSymbol cop rejects any literal livecheck URL in a formula whose
  # only `url`s are per-platform.)
  livecheck do
    url :homepage
    regex(%r{href=["']?/cli/v?(\d+(?:\.\d+)+)/checksums\.txt}i)
  end

  on_macos do
    on_arm do
      url "https://get.nimbusland.ca/cli/v0.1.0/nimbus_0.1.0_darwin_arm64.tar.gz"
      sha256 "755769442df6585edaf009e340a8e42ad6bbae064649b7764605dec4f8e60788"
    end
    on_intel do
      url "https://get.nimbusland.ca/cli/v0.1.0/nimbus_0.1.0_darwin_amd64.tar.gz"
      sha256 "5fe9e8862b224005f43c63673c9d8cfcde2be0198e46525ec41b75dbc218c3f5"
    end
  end

  on_linux do
    on_arm do
      url "https://get.nimbusland.ca/cli/v0.1.0/nimbus_0.1.0_linux_arm64.tar.gz"
      sha256 "d1253a3f4ef4c2dc7b674331a760f95e0c62965f39383e0032348d1b85e775fa"
    end
    on_intel do
      url "https://get.nimbusland.ca/cli/v0.1.0/nimbus_0.1.0_linux_amd64.tar.gz"
      sha256 "841fce6cd54901d974c283393bb969a6242856e6f4cb3d49f15afe06cf66a77e"
    end
  end

  def install
    bin.install "nimbus"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nimbus version")
  end
end
