# Generated by `nimbus-release render-formula` for the 0.3.0 release.
# Do not edit by hand: the next release overwrites it.
class Nimbus < Formula
  desc "Deploy and manage apps on Nimbus Land"
  homepage "https://get.nimbusland.ca"
  version "0.3.0"
  license :cannot_represent

  # Stable versions only: pre-release links ("v0.6.0-rc.1/") don't match.
  # (A JSON livecheck on /cli/latest.json would be nicer, but Homebrew's
  # LivecheckUrlSymbol cop rejects any literal livecheck URL in a formula whose
  # only `url`s are per-platform.)
  livecheck do
    url :homepage
    regex(%r{href=["']?/cli/v?(\d+(?:\.\d+)+)/checksums\.txt}i)
  end

  on_macos do
    on_arm do
      url "https://get.nimbusland.ca/cli/v0.3.0/nimbus_0.3.0_darwin_arm64.tar.gz"
      sha256 "daa6337c8846d0ea538720e662d464dd59b87ba50a4356a9c6aa250d8314313a"
    end
    on_intel do
      url "https://get.nimbusland.ca/cli/v0.3.0/nimbus_0.3.0_darwin_amd64.tar.gz"
      sha256 "98d8eb20b79e9e0373aecdcf6ff6fb6f15888a83696d55210ff5ff216ac7ce0e"
    end
  end

  on_linux do
    on_arm do
      url "https://get.nimbusland.ca/cli/v0.3.0/nimbus_0.3.0_linux_arm64.tar.gz"
      sha256 "bfdfe7a03f6036aa0d68a0f6bc7683a6c4585352b1da4f7177d3ad75eb4cea0d"
    end
    on_intel do
      url "https://get.nimbusland.ca/cli/v0.3.0/nimbus_0.3.0_linux_amd64.tar.gz"
      sha256 "bbaa315a1dde60a031984346e350538d3b569bae02d76a99769df18b8f8a222b"
    end
  end

  def install
    bin.install "nimbus"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nimbus version")
  end
end
