# Generated by `nimbus-release render-formula` for the 0.2.0 release.
# Do not edit by hand: the next release overwrites it.
class Nimbus < Formula
  desc "Deploy and manage apps on Nimbus Land"
  homepage "https://get.nimbusland.ca"
  version "0.2.0"
  license :cannot_represent

  # Stable versions only: pre-release links ("v0.6.0-rc.1/") don't match.
  # (A JSON livecheck on /cli/latest.json would be nicer, but Homebrew's
  # LivecheckUrlSymbol cop rejects any literal livecheck URL in a formula whose
  # only `url`s are per-platform.)
  livecheck do
    url :homepage
    regex(%r{href=["']?/cli/v?(\d+(?:\.\d+)+)/checksums\.txt}i)
  end

  on_macos do
    on_arm do
      url "https://get.nimbusland.ca/cli/v0.2.0/nimbus_0.2.0_darwin_arm64.tar.gz"
      sha256 "84503562272dc9a268d79d24e7649ae957ad78efa06eed83d5a4bad209f0f1ed"
    end
    on_intel do
      url "https://get.nimbusland.ca/cli/v0.2.0/nimbus_0.2.0_darwin_amd64.tar.gz"
      sha256 "ed45c554561285feaeb0bc46b27a76e009d979111325df38ec247d0b11e80971"
    end
  end

  on_linux do
    on_arm do
      url "https://get.nimbusland.ca/cli/v0.2.0/nimbus_0.2.0_linux_arm64.tar.gz"
      sha256 "04de4ba4d27c4d4c2b9afff0882402b102d9fc2fdfdb47fe6b5950a880f6ad80"
    end
    on_intel do
      url "https://get.nimbusland.ca/cli/v0.2.0/nimbus_0.2.0_linux_amd64.tar.gz"
      sha256 "8386cd0ef52af212c38c45939ba3951930343758106dbae9c0751c7cf147399e"
    end
  end

  def install
    bin.install "nimbus"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nimbus version")
  end
end
